### ISSUE TITLE
Some attributes in <media> remain empty for Supplementary materials

### ISSUE THREAD

**Issue by brokentool** [bozhink/ProcessingTools#14]
Не зная аз ли бъркам нещо, но някои атрибути на всички supplementary materials в таг <media> остават празни.

e.g.: <media xlink:href="" mimetype="" mime-subtype="" position="float" orientation="portrait" xlink:type="simple" />

Налага се да гледам от стари xml файлове и да ги допълвам на ръка.

**Comment by bozhink** [comment]
В `<media>` трябва ръчно да се въведе стойност на атрибута `@xlink:href`, т.е. името на файла, след това трябва да се извика resolver-а на медия-типове (опция `-m`), който би тябвало да зададе стойност на атрибутите `@mimetype` и `@mime-subtype`. Ако не разпознае типовете по разширението на файла, би трябвало да зададе стойности `@mimetype='unknown'` и `@mime-subtype='unknown'`.

Ако има проблем с връзката с базата, където се пазят медия-типовете, би трябвало да мисли около 30 сек. и за изпише грешка.

При следващ проблем, моля да бъде прикачен изходния файл, в който нещата се чупят.

**Comment by brokentool** [comment]
Благодаря за отговора и извинявай, че не можах още в петък да пиша. Проблемът беше в това, че съм забравил, че трябва ръчно да се посочи пътя към файла в temp сървъра. Сега всичко е ОК.

За в бъдеще, ще прикачвам необходимите файлове.
