### ISSUE TITLE
local site not loading CSS

### ISSUE THREAD

**Issue by brokentool** [bozhink/ProcessingTools#18]
Здравей Божине,

Извинявай, че те занимавам, но имаме проблем с локалния сайт. Инсталирахме го на лаптопа на Ангел (който се върна на работа тук), но не зарежда CSS-а изобщо.

В конзолата на firefox не дава грешки, но в тази на хром изписва следното:

`protools.loc/:1 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'persistentFlag' of null
    at Object.c [as tooltip_isAuthenticated] (chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/content/tooltips/tooltip_check.js:3:1291)
    at c (chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/js/common/Browser.js:3:3911)
protools.loc/:1 Error in event handler for (unknown): SyntaxError: Unexpected token u in JSON at position 0
    at chrome-extension://boamfheepdiallipiieadpmnklbhadhc/hotkeyListener.js:1:80`

Имаш ли представа какъв е проблемът?

**Comment by bozhink** [comment]
Първо: коя версия използвате? Ако pull-вате от GitHub използвайте само master-branch-а. В другите branch-ове понякога правя тестове и не гарантирам, че работят.

После: ако прекомпилирате кода, не забравайте за сайта да компилирате CSS и JS (използва NPM от NodeJS).

Като гледам грешката, допускам че не се зарежда правилно един от външните пакети, които трябва да се свалят с Bower - пакетът tether, от който зависи bootstrap. Вижте дали след извикване на `npm install` се появявят нужните директории в папка bower_components. Вероятно скоро подръжката на Bower ще бъде преустановена и може и оттам да идва проблемът.

Ако не стане прегледайте описаните пътеки във файла ProcessingTools.Web.Documents/App_Start/BundleConfig.cs дали отговарят на реалните. После изтрийте bin и obj и прекомпилирайте в Debug.

Ако нищо от това не помогне, пробвайте delete-all + copy-paste от друга работеща инсталация  + stop + start на web-сайта (не restart).

Въпрос: грешката има ли нещо общо с <https://github.com/Reviewable/Reviewable/issues/382>

**Comment by brokentool** [comment]
Благодаря ти много за бързия отговор.

Истината е, че сложихме сайта по метода на последното ти предложение - копирахме всичко от моя компютър, не сме компилирали нищо. По този начин всичко тръгна коректно на машините на Любо и Пламен, но не и на тази на Ангел. Не съм сигурен, че бих могъл да се справя с NodeJS инсталацията, която само съм те виждал да правиш веднъж.

Пробвахме стоп-старт, но няма промяна. Ако има нещо извън папките GitHub, inetpub и bin, което трябва да се копира, вероятно не сме.

**Comment by bozhink** [comment]
Тогава може да е проблем с plug-in на браузерите. Опитайте напр. с Opera.

Друг въпрос: избрахте ли порт различен от 80 за сайта при конфигурирането на IIS? Добавихте ли в hosts файла mapping за локалния сайт, на който да го достъпвате?

Грешката ще я потърся по-късно, а засега Ангел може просто да се свърже към някой от вашите локални сайтове и да си регистрира свой потребител (свързването е по IP адрес на машината + port, като машината трябва да е видима в локалната мрежа).

**Comment by brokentool** [comment]
Добавили сме нужното в hosts файла, пробвахме порт 8080 току-що, но отново не зарежда.

Машината ми е видима за Ангел в мрежата, намерих си и публичното ip, но не съм сигурен какво точно трябва да изпишем в браузъра, за да тръгне.

ip + port = "213.145.125.72:8080"

Извинявай, че те занимавам с това.

**Comment by bozhink** [comment]
Адресът трябва да е нещо от сорта 192.168.*.*, но може да пробвате и 213....

Ако не си сигурен какъв е адресът и портът може да сканираш мрежата с tool като Fing например (приложение за Android) - пускаш сканиране на мрежата, кликваш върху машината си, избираш Scan services; за HTTP сервизите ще ти позволи директно отваряне в браузера на телефона, където ще видиш адреса, на който да се свържеш от компютър.

**Comment by brokentool** [comment]
справихме се с това да го подкараме на моята машина, с помощта на Георги.

**Comment by bozhink** [comment]
Опитах с чист build от master-branch-а и при мен сайтът работи без проблеми.

Прегледайте дали са правилно зададени пътеките и адресите в CommonAppSettings.config и дали Web.config-а на сайта сочи правилно към този файл - за IIS двата config-а трябва да са на едно storage устройство (напр. диск C:). Редактирайте ConnectionStrings на Web.config-а, ако няма SQL Server на адрес `Data Source=(localdb)\MSSQLLocalDB` (този се инсталира заедно с VS) - базата е необходима за потребителите, останалите данни са пренасочени към MongoDB.

Ако искате да пре-компилирате:
+ pull на master-branch-а
+ build + rebuild във VS в Debug configuration
+ отваряте cmd или powershell в директорията на проекта ProcessingTools.Web.Documents
   * `npm install`
   * `npm run build`

Трябва ви .NET 4.6.2. Няма да е излишно (но не е задължително) dotnet core със съвместимост с dotnet standard 2.0 <https://www.microsoft.com/net/download/core>

**Comment by brokentool** [comment]
Благодарско, ще тестваме.
