### ISSUE TITLE
Reference tagging in PMT

### ISSUE THREAD

**Issue by brokentool** [bozhink/ProcessingTools#19]
Ако първият текст след годината в референция e таксон, pmt не успява да тагне този текст и <fake-tag> остава празен. Остават само авторите, годината и (ако има) линковете накрая.

**Пример:** Kan YH, Qin WM, Zhou LW (2016) _Hyphodontia mollissima_ sp. nov. (Schizoporaceae, Hymenochaetales) from Hainan, southern China. Mycoscience 58: 297–301. https://doi.org/10.1016/j.myc.2017.04.003

Губи се "_Hyphodontia mollissima_ sp. nov. (Schizoporaceae, Hymenochaetales) from Hainan, southern China. Mycoscience 58: 297–301."

**Comment by bozhink** [comment]
Проблемът е, че записът е нещо като 

> (2016)<italic> Hyphodontia

т.е. няма интервал преди <italic>. Трябва да се прегледат регулярните изрази, които извършват началното разделяне на референцията. Ако не знаеш къде се редактират, попитай Теодор.
