### ISSUE TITLE
Three Minor Issues with ProcessingTools

### ISSUE THREAD

**Issue by brokentool** [bozhink/ProcessingTools#39]
Здравей @bozhink ,

Намерихме три проблема при ползване на новата версия, на които искам да ти обърна внимание:

1. При наличието на таксон тагове в <article-title> във <front>, заглавието се цепи на редове и не излиза коректно в Non-XML citation и в Crossref XML-a. Това е основния проблем, другите са съвсем дребни.

2. Сайтът не пази логин сесията дълго, remember me тик бокс-а не изглежда да работи коректно. Налага се да се логваме наново по няколко пъти на ден.

3. Когато използваш опцията Edit XML на даден документ към дадена статия, горе в ляво, в менюто, има опцията Edit HTML, което в списъка с документи се казва Preview HTML. Отначало това ни обърка малко, но също не е проблем, само го споменавам.

**Comment by bozhink** [comment]
Здравей @brokentool ,

На staging е качена версия 0.1.1:

По точка 2 - времето на живот на cookie беше 60 мин; сега е 10 ч. Би трябвало да е достатъчно.

По точка 3 - вече надписът е Preview HTML навсякъде.

По точка 1 - Не разбирам какво означава "Non-XML citation", а "Crossref XML" не помня да генерирам. Ако е възможно, качете примерен проблемен XML файл.

Единствено мога да отбележа, че когато се отвори документ като HTML, редактира се и се запише, то записаният XML е нормализиран, т.е. изглежда от вида
`<tp:taxon-name xmlns:tp="http://www.plazi.org/taxpub"><tp:taxon-name-part taxon-name-part-type="order">Trichoptera</tp:taxon-name-part></tp:taxon-name>`,
а не
`<tp:taxon-name><tp:taxon-name-part taxon-name-part-type="order">Trichoptera</tp:taxon-name-part></tp:taxon-name>`.
Тази нормализация може да обърква serializer-а, който използвате за генериране на описаните данни и документи. Ако XML-ът се прекара през Tagger-а, той би трябвало да де-нормализира документа и да изкара namespce-ите най-отгоре (на `article`-тагът).

Може би нормализацията създава проблемите от точка 1, но за да направя нужната промяна ми трябва потвърждение, че де-нормализацията на XML-а оправя тези грешки.

**Comment by brokentool** [comment]
Здравей,

През последните няколко дни не успях да репликирам проблема от т. 1, вероятно ние при експорта сме създали този проблем някак, но ако се появи отново, ще се постарая да кача тук всичко необходимо. Иначе "Non-XML citation" е цитацията, която се генерира в Non-XML таб-а в PJS. Така или иначе, ще видим дали ще се появи отново проблема.
